### PR TITLE
Fix residual flake issues

### PR DESCRIPTION
**Pull request by adivijaykumar**
Needs #12. Solves some remaining flake/black issues. Here are the three that remain, which I was unsure how to solve. @prayush any comments on these?

```
nrcatalogtools/maya.py:98:23: F821 undefined name 'ValueErwaveform_filepath_from_simnameror'
nrcatalogtools/rit.py:632:9: F841 local variable 'wf_local_path' is assigned to but never used
nrcatalogtools/waveform.py:100:21: F841 local variable 'nr_group' is assigned to but never used
```

### CODE REVIEW

**Comment by prayush** [comment]
> Needs https://github.com/gwnrtools/nr-catalog-tools/pull/12. Solves some remaining flake/black issues. Here are the three that remain, which I was unsure how to solve. @prayush any comments on these?

> nrcatalogtools/maya.py:98:23: F821 undefined name 'ValueErwaveform_filepath_from_simnameror'

this should be fixed on rebase

> nrcatalogtools/rit.py:632:9: F841 local variable 'wf_local_path' is assigned to but never used
> nrcatalogtools/waveform.py:100:21: F841 local variable 'nr_group' is assigned to but never used

if these persist on rebase, the two variables should be removed

**Comment by adivijaykumar** [comment]
Rebased. This PR requires some review, especially [d28f706](https://github.com/gwnrtools/nr-catalog-tools/pull/13/commits/d28f70663b70521f4aedb132a83b030fc00a3746) to make sure I haven't altered the intended behaviour. However, needs #12 to merge.

**Comment by prayush** [comment]
#12 is merged. Shall we mark this ready for review @adivijaykumar ?

**Comment by adivijaykumar** [comment]
#18 has introduced quite a few breaking changes to the package. Also including fixes to them here. Summary below:


```
./nrcatalogtools/lvc.py:429:13: F821 undefined name 'np'
./nrcatalogtools/lvc.py:431:12: F821 undefined name 'np'
./nrcatalogtools/lvc.py:432:12: F821 undefined name 'np'
./nrcatalogtools/lvc.py:447:15: F821 undefined name 'np'
./nrcatalogtools/lvc.py:448:15: F821 undefined name 'np'
./nrcatalogtools/lvc.py:450:12: F821 undefined name 'np'
./nrcatalogtools/lvc.py:450:33: F821 undefined name 'np'
./nrcatalogtools/lvc.py:453:5: F841 local variable 'LNhat' is assigned to but never used
./nrcatalogtools/lvc.py:453:20: F821 undefined name 'np'
./nrcatalogtools/lvc.py:457:5: F841 local variable 'nhat' is assigned to but never used
./nrcatalogtools/lvc.py:457:21: F821 undefined name 'np'
./nrcatalogtools/lvc.py:461:19: F821 undefined name 'LNhatx'
./nrcatalogtools/lvc.py:462:19: F821 undefined name 'LNhaty'
./nrcatalogtools/lvc.py:463:19: F821 undefined name 'LNhatz'
./nrcatalogtools/lvc.py:464:18: F821 undefined name 'nhatx'
./nrcatalogtools/lvc.py:465:18: F821 undefined name 'nhaty'
./nrcatalogtools/lvc.py:466:18: F821 undefined name 'nhatz'
./nrcatalogtools/lvc.py:495:5: F841 local variable 'IntParams' is assigned to but never used
./nrcatalogtools/lvc.py:495:17: F821 undefined name 'GetInterpRefValuesFromH5File'
./nrcatalogtools/lvc.py:498:13: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:498:47: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:499:13: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:499:47: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:500:13: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:500:47: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:503:12: F821 undefined name 'np'
./nrcatalogtools/lvc.py:504:5: F841 local variable 'nhat' is assigned to but never used
./nrcatalogtools/lvc.py:504:19: F821 undefined name 'np'
./nrcatalogtools/lvc.py:508:15: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:509:15: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:510:15: F821 undefined name 'RefParams'
./nrcatalogtools/lvc.py:512:13: F821 undefined name 'np'
./nrcatalogtools/lvc.py:513:21: F821 undefined name 'np'
./nrcatalogtools/lvc.py:518:19: F821 undefined name 'LNhatx'
./nrcatalogtools/lvc.py:519:19: F821 undefined name 'LNhaty'
./nrcatalogtools/lvc.py:520:19: F821 undefined name 'LNhatz'
./nrcatalogtools/lvc.py:521:18: F821 undefined name 'nhatx'
./nrcatalogtools/lvc.py:522:18: F821 undefined name 'nhaty'
./nrcatalogtools/lvc.py:523:18: F821 undefined name 'nhatz'
./nrcatalogtools/lvc.py:628:51: W605 invalid escape sequence '\p'
./nrcatalogtools/lvc.py:669:5: F841 local variable 'tol' is assigned to but never used
./nrcatalogtools/lvc.py:697:5: F841 local variable 'ReqDefAttrsSXS' is assigned to but never used
./nrcatalogtools/lvc.py:719:24: F821 undefined name 'GetRefTimeFromRefFreq'
./nrcatalogtools/lvc.py:721:42: F821 undefined name 'CheckInterpReq'
./nrcatalogtools/lvc.py:722:13: E722 do not use bare 'except'
./nrcatalogtools/lvc.py:724:121: E501 line too long (129 > 120 characters)
./nrcatalogtools/lvc.py:728:34: F821 undefined name 'CheckInterpReq'
./nrcatalogtools/lvc.py:730:15: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
./nrcatalogtools/lvc.py:735:16: F821 undefined name 'GetRefTimeFromMetadata'
./nrcatalogtools/lvc.py:742:40: F821 undefined name 'CheckNRAttrs'
./nrcatalogtools/lvc.py:746:26: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
./nrcatalogtools/lvc.py:752:48: F821 undefined name 'CheckNRAttrs'
./nrcatalogtools/lvc.py:754:32: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
./nrcatalogtools/lvc.py:758:33: F821 undefined name 'ComputeLALSourceFrameFromSXSMetadata'
./nrcatalogtools/lvc.py:761:121: E501 line too long (124 > 120 characters)
./nrcatalogtools/lvc.py:765:29: F821 undefined name 'GetRefVals'
./nrcatalogtools/lvc.py:768:25: F821 undefined name 'GetRefVals'
./nrcatalogtools/lvc.py:770:17: E712 comparison to True should be 'if cond is True:' or 'if cond:'
./nrcatalogtools/lvc.py:789:48: F821 undefined name 'CheckNRAttrs'
./nrcatalogtools/lvc.py:791:30: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
./nrcatalogtools/lvc.py:793:121: E501 line too long (144 > 120 characters)
./nrcatalogtools/lvc.py:796:25: F821 undefined name 'ComputeLALSourceFrameByInterp'
./nrcatalogtools/lvc.py:815:14: F821 undefined name 'np'
./nrcatalogtools/lvc.py:816:13: F821 undefined name 'np'
./nrcatalogtools/lvc.py:819:18: F821 undefined name 'np'
./nrcatalogtools/lvc.py:820:18: F821 undefined name 'np'
./nrcatalogtools/lvc.py:821:20: F821 undefined name 'np'
./nrcatalogtools/lvc.py:822:20: F821 undefined name 'np'
./nrcatalogtools/lvc.py:824:18: F821 undefined name 'np'
./nrcatalogtools/lvc.py:835:14: F821 undefined name 'np'
./nrcatalogtools/lvc.py:836:23: F821 undefined name 'np'
./nrcatalogtools/lvc.py:841:13: F821 undefined name 'np'
./nrcatalogtools/lvc.py:854:27: F821 undefined name 'np'
./nrcatalogtools/lvc.py:855:31: F821 undefined name 'np'
./nrcatalogtools/lvc.py:856:32: F821 undefined name 'np'
./nrcatalogtools/lvc.py:857:27: F821 undefined name 'np'
./nrcatalogtools/lvc.py:864:39: F821 undefined name 'np'
./nrcatalogtools/lvc.py:870:19: F821 undefined name 'np'
./nrcatalogtools/lvc.py:870:40: F821 undefined name 'np'
./nrcatalogtools/lvc.py:872:17: F821 undefined name 'np'
./nrcatalogtools/lvc.py:872:31: F821 undefined name 'np'
./nrcatalogtools/lvc.py:877:23: F821 undefined name 'np'
./nrcatalogtools/lvc.py:878:21: F821 undefined name 'np'
./nrcatalogtools/lvc.py:878:35: F821 undefined name 'np'
./nrcatalogtools/lvc.py:888:14: F821 undefined name 'np'
./nrcatalogtools/lvc.py:889:14: F821 undefined name 'np'
./nrcatalogtools/lvc.py:890:12: F821 undefined name 'np'
./nrcatalogtools/lvc.py:891:12: F821 undefined name 'np'
./nrcatalogtools/lvc.py:896:17: F821 undefined name 'np'
./nrcatalogtools/lvc.py:901:15: F821 undefined name 'np'
./nrcatalogtools/lvc.py:904:19: F821 undefined name 'np'
./nrcatalogtools/lvc.py:905:28: F821 undefined name 'np'
./nrcatalogtools/lvc.py:906:17: F821 undefined name 'np'
./nrcatalogtools/lvc.py:907:26: F821 undefined name 'np'
./nrcatalogtools/lvc.py:909:5: F841 local variable 'salpha' is assigned to but never used
./nrcatalogtools/lvc.py:912:13: F821 undefined name 'np'
```

**Comment by adivijaykumar** [comment]
This is now ready for review. However, I have not fixed a lot of the issues introduced by #18 since they are pretty serious and I don't think I will be able to do a very good job at it. Have created #19 for the same.

**Review by prayush — APPROVED** [review]

**Pull request merged**
