### PR TITLE
Fix polarization convention

### PR DESCRIPTION
**Pull request by vaishakp**
Conjugate waveform to comply with lal convention.

### CODE REVIEW

**Review by prayush — CHANGES_REQUESTED** [review]
Good catch. 

Can you please add a quick unit test for convention also, so we catch this deviation going forward. 

E.g. generate a lalsimulation waveform (say, using SEOBNRv3) and compare both of its polarizations with NR data. For this purpose it'll be easiest to pick the same sim whose data you've included as part of this repo (so unit tests don't keep downloading data all the time). All we will need from the comparison is just a basic correlation of signs, as with the opposite convention the cross (x) polarization gets an overall minus (-) sign.

**Comment by vaishakp** [comment]
> Good catch.
> 
> Can you please add a quick unit test for convention also, so we catch this deviation going forward.
> 
> E.g. generate a lalsimulation waveform (say, using SEOBNRv3) and compare both of its polarizations with NR data. For this purpose it'll be easiest to pick the same sim whose data you've included as part of this repo (so unit tests don't keep downloading data all the time). All we will need from the comparison is just a basic correlation of signs, as with the opposite convention the cross (x) polarization gets an overall minus (-) sign.

Actually the test in 

> Good catch.
> 
> Can you please add a quick unit test for convention also, so we catch this deviation going forward.
> 
> E.g. generate a lalsimulation waveform (say, using SEOBNRv3) and compare both of its polarizations with NR data. For this purpose it'll be easiest to pick the same sim whose data you've included as part of this repo (so unit tests don't keep downloading data all the time). All we will need from the comparison is just a basic correlation of signs, as with the opposite convention the cross (x) polarization gets an overall minus (-) sign.

This test is included in #33, where it also compares the waveforms pointwise.

**Comment by prayush** [comment]
> This test is included in https://github.com/gwnrtools/nr-catalog-tools/pull/33, where it also compares the waveforms pointwise.

then this looks ready to merge.

**Review by prayush — APPROVED** [review]

**Comment by prayush** [comment]
> > This test is included in #33, where it also compares the waveforms pointwise.
> 
> Then this looks ready to merge. @vaishakp could you remove the "draft" status!

Nvm, just did that :)

**Pull request merged**
