### PR TITLE
Add Waveformtools to requirements.txt

### PR DESCRIPTION
**Pull request by prayush**
Add @vaishakp's `waveformtools` to requirements.txt. Its currently only used in a unit test.

### CODE REVIEW

**Comment by vaishakp** [comment]
Before this is merged,  waveformtools must be in pypi right?

**Comment by prayush** [comment]
> Before this is merged, waveformtools must be published in pypi right?

No, `pip` can often install packages from their git repo directly. And this definitely seems to be the case for `waveformtools`. E.g. try `pip install git+https://gitlab.com/vaishakp/waveformtools@main`.

**Comment by prayush** [comment]
> Will `waveformtools @ git+https://gitlab.com/vaishakp/waveformtools@main` then work in requirements.txt (untill i publish)?

yes, I've tested it. I suggest you also verify by saving the following as  a txt file and pip installing it:

```
# Modules to install
numpy
scipy
lalsuite
ligo-common
pycbc
pandas
sxs[ecosystem]
waveformtools @ git+https://gitlab.com/vaishakp/waveformtools@main
```

**Comment by vaishakp** [comment]
Sure. We can go ahed. I will check soon.

**Pull request merged**
