### PR TITLE
Bugfix generate polarizations

### PR DESCRIPTION
**Pull request by vaishakp**
This commit adds a feature and fixes some bugs in the computation of the waveform polarizations.

Feature add:
1. Inherit `WaveformModes.filepath` and `WaveformModes.sim_metadata` from catalog for SXS.
2. Presently, MAYA data does not provide the NR `t_ref` but instead `Omega`. Added method to compute this from `Omega` and the l2m2 orbital phasing.

Changes:
1. Move the computation of reference orbital phase from lvc to waveforms.

Bug fix:
1. fixed variable mismatch in `get_td_waveform` method.

### CODE REVIEW

**Comment by prayush** [comment]
@vaishakp - this needs a pull and rebase to resolve conflicts

**Comment by vaishakp** [comment]
> @vaishakp - this needs a [pull and rebase](https://github.com/openedx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to resolve conflicts

On pull and rebase, the pull request is not getting updated. This is probably due to the fact that my fork now contains commits from another repo (streamline imports). Should I create another PR, or just resolve them directly here without a pull and rebase?

**Comment by vaishakp** [comment]
> > @vaishakp - this needs a [pull and rebase](https://github.com/openedx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) to resolve conflicts
> 
> On pull and rebase, the pull request is not getting updated. This is probably due to the fact that my fork now contains commits from another repo (streamline imports). Should I create another PR, or just resolve them directly here without a pull and rebase?

It turns out that the reason why this PR was not updated was that github was down yesterday. This can be now be merged.

**Comment by prayush** [comment]
@vaishakp the oldest commit of this PR `9755781639417e6de3380697be865a5eedb897dc` - has already been merged into master. Why is it showing up here?

**Comment by vaishakp** [comment]
> @vaishakp the oldest commit of this PR `9755781639417e6de3380697be865a5eedb897dc` - has already been merged into master. Why is it showing up here?

I think this is the default behaviour of github when squash + merge is selected. When rebasing from the common ancestor commit, github does not update its PR wrt the changes in the target branch. I don't know about the implications.

Should we try not squashing the commits?

**Pull request closed without merging**
